### ISSUE TITLE
need 1.19.4

### ISSUE THREAD

**Issue by BiscuitEat2r** [IrisDimensions/rrtoverworld#1]
need 1.19.4 ww

**Comment by RePixelatedMC** [comment]
I really dont understand why no one reads the description since it says that it got M E R G E D with overworld so rrt is basicaly the new default pack

**Comment by RePixelatedMC** [comment]
or is there a language barrier? oh well either way you know now

**Comment by BiscuitEat2r** [comment]
> or is there a language barrier? oh well either way you know now

sry imnot a English speakers Therefore, some sentences may cause misunderstanding for me.
